# All messages that can be sent by the plugin
messages:
  tips:
    help-command: "Astuce: utilise l'argument help à la fin d'une commande pour afficher l'aide."
  error:
    no-permission: "§cVous n'êtes pas autorisé à faire ça (§7[permission]§c)."
    use-only-in-game: "§cCette commande est uniquement disponible dans le jeu."
    misuse-command: "§cMauvaise utilisation de la commande."
    unknown-player: "§cLe joueur §7[player]§c n'existe pas ou n'a jamais joué sur le serveur."
  help:
    usage: "§cUtilisation: §e[parent-command-usage]"
    description: "§cDescription: §e[parent-command-description]"
  confirm-command:
    confirm: "§6Pour confirmer votre commande, executez la commande §f[confirm-command-usage]§6 dans les 10 prochaines secondes."
    request-cancelled: "§cDélai de confirmation de la command dépassé."
    no-command-to-confirm: "§cVous n'avez pas de commande à confirmer."
  reward:
    added:
      any: "§cAucune récompense n'est obtenable pour le moment."
      one: "§aVous avez récupéré une récompense."
    get:
      any: "§cAucune récompense récuperée."
      one: "§aVous avez récuperé une récompense."
      multiple: "§aVous avez récuperé [nb-rewards] récompenses."
  topvote:
    header:
      all-time: "§b===== Meilleur voteurs ====="
      year: "§b===== Meilleurs voteurs de l'année ====="
      month: "§b===== Meilleurs voteurs du mois ====="
      week: "§b===== Meilleurs voteurs de la semaine ====="
      day: "§b===== Meilleurs voteurs du jours ====="
    voting-user-line:
      first: "§e§l1. §f[username] §d([nb-votes])"
      second: "§7§l2. §f[username] §d([nb-votes])"
      third: "§6§l3. §f[username] §d([nb-votes])"
      other: "§3§l[rank]. §f[username] §d([nb-votes])"
    footer: "§b===== Page [current-page] sur [last-page] ====="
  vote:
    never:
      all-time: "§e[player] n'a jamais voté pour le serveur."
      year: "§e[player] n'a pas voté pour le serveur cette année."
      month: "§e[player] n'a pas voté pour le serveur ce mois-ci."
      week: "§e[player] n'a pas voté pour le serveur cette semaine."
      day: "§e[player] n'a pas voté pour le serveur aujourd'hui."
    one-or-more:
      all-time: "§e[player] a voté [nb-votes] fois pour le serveur."
      year: "§e[player] a voté [nb-votes] fois pour le serveur cette année."
      month: "§e[player] a voté [nb-votes] fois pour le serveur ce mois-ci."
      week: "§e[player] a voté [nb-votes] fois pour le serveur cette semaine."
      day: "§e[player] a voté [nb-votes] fois pour le serveur aujourd'hui."
  admin:
    fakevote:
      one: "§aUn vote a été simulé. Vous avez récupéré [nb-given-rewards] récompense."
      multiple: "§a[nb-fakevote] votes ont été simulés. Vous avez récupéré [nb-given-rewards] récompenses."
      must-greater-than-0: "§cLe nombre de vote à simuler doit être supérieur à 0."
    rewards-group:
      rewards-group-already-exists: "§cLe groupe de récompenses §4[rewards-group-name]§c existe déjà."
      rewards-group-created: "§aLe groupe de récompenses §2[rewards-group-name]§a a été créé."
      deleted: "§aLe groupe de récompense §2[rewards-group-name]§a a été supprimé."
      unable-to-delete: "§cImpossible de supprimer le groupe de récompense §7[rewards-group-name]§c."
      unknown-rewards-group: "§cLe groupe de récompenses §4[rewards-group-name]§c n'existe pas."
      rewards-group-activated: "§aLe groupe de récompenses §2[rewards-group-name]§a est maintenant activé."
      add-reward:
        nothing-in-main-hand: "§cVous devez tenir l'item à ajouter dans votre main principal."
        successfully-added-reward: "§aNouvelle récompense ajoutée au groupe §2[rewards-group-name]§a avec un pourcentage d'obtention de §2[percentage]."

# All string used in the different interfaces
gui:
  navigationButton:
    previousPage: "§r§a← Page précédente"
    nextPage: "§r§aPage suivante →"
  bagSee:
    title: "Sac de récompenses"
    getRewards: "§r§eRécuperer les récompenses"
  stat:
    title: "Récompenses obtenables"
  admin:
    rewards-group-list:
      title: "Groupes de récompenses"
      enabled: "§9Activé"
      help-for-activate: "§7SHIFT + LEFT_CLICK pour activer"
    rewards-group-view:
      title: "[rewards-group-name]"
      rewards-group-icon:
        nb-rewards: "§7Nombre de récompenses: [nb-rewards]"
      reward-view:
        percentage: "§7Pourcentage: [percentage]%"
        real-percentage: "§7Pourcentage réel: [real-percentage]%"

# Commands
commands:
  help:
    description: "Affiche l'aide de la commande"
    usage: "[parent-command-usage] help"
  votereward:
    description: "Commande de base de VoteReward"
    usage: "/vr"
    parameters: "<bag | admin | topvote | confirm >"
    confirm:
      description: "Permets de valider l'éxecution d'une commande demandant une confirmation"
      usage: "/vr confirm"
    bag:
      description: "Permet de gérer son sac de récompenses"
      usage: "/vr bag"
      parameters: "<see | get>"
      see:
        description: "Permet de voir son sac de récompenses"
        usage: "/vr bag see"
      get:
        description: "Permet de récuperer ses récompenses"
        usage: "/vr bag get"
        parameters: "[amount]"
    admin:
      description: "Permet d'exécuter des commandes admin"
      usage: "/vr admin"
      parameters: "<fakevote | bag | rewardsgroups>"
      fakevote:
        description: "Permet de simuler un vote"
        usage: "/vr admin fakevote"
        parameters: "[amount]"
      bag:
        description: "Permet de gérer les bags d'autres joueurs"
        usage: "/vr admin bag"
        parameters: "<get | see>"
        get:
          description: "Permet de récuperer les récompenses d'un autre joueur"
          usage: "/vr admin bag get"
          parameters: "<player> [amount]"
        see:
          description: "Permet de voir les récompenses d'un autre joueur"
          usage: "/vr admin bag see"
          parameters: "<player>"
      rewardsgroups:
        description: "Permets de gérer les groupes de récompenses"
        usage: "/vr admin rewardsgroups"
        parameters: "<create | delete | list | activate>"
        create:
          description: "Permet de créer un nouveau groupe de récompenses"
          usage: "/vr admin rewardsgroups create"
          parameters: "<name>"
        delete:
          description: "Permet de supprimer un groupe de récompenses"
          usage: "/vr admin rewardsgroups delete"
          parameters: "<rewards-group-name>"
        list:
          description: "Permet de voir la liste des groupes de récompenses"
          usage: "/vr admin rewardsgroups list"
          parameters: "[page]"
        activate:
          description: "Permet de définir le groupe de récompenses actif"
          usage: "/vr admin rewardsgroups activate"
          parameters: "<rewards-group-name>"
      rewardsgroup:
        description: "Permet de gérer un groupe de récompenses"
        usage: "/vr admin rewardsgroup"
        parameters: "<rewards-group-name>"
        <rewards-group-name>:
          description: "Permet de gérer un groupe de récompenses"
          usage: "/vr admin rewardsgroup <rewards-group-name>"
          parameters: "<addReward | see>"
          addreward:
            description: "Permet d'ajouter l'item dans la main du joueur en tant que récompense."
            usage: "/vr admin rewardsgroup <rewards-group-name> addreward"
            parameters: "[percentage]"
          see:
            description: "Permet de visualiser un groupe de récompenses"
            usage: "/vr admin rewardsgroup <rewards-group-name> see"
            parameters: "[page]"
    topvote:
      description: "Permet de voir les meilleurs voteurs du jour/semaine/mois/année"
      usage: "/vr topvote"
      parameters: "[day | week | month | year | all-time] [page]"
    vote:
      description: "Permet de voir le nombre de vote d'un joueur "