main: fr.lataverne.votereward.VoteReward

name: VoteReward

description: Manage the vote rewards and the bags

authors:
  - syuko

version: 2.0.0

api-version: 1.18

permissions:
  votereward.bag:
    description: Allows bag command usage
    default: true
    children:
      votereward.bag.get:
        description: Allows to use /votereward bag get
        default: true
      votereward.bag.see:
        description: Allows to use /votereward bag see
        default: true