main: fr.lataverne.votereward.VoteReward

name: VoteReward

description: Manage the vote rewards and the bags

authors:
  - syuko

version: 2.0.0

api-version: 1.18

permissions:
  votereward.bag:
    description: Allows bag commands usage
    default: true
    children:
      votereward.bag.get:
        description: Allows using /votereward bag get
        default: true
      votereward.bag.see:
        description: Allows using /votereward bag see
        default: true
  votereward.admin:
    description: Allows admin command usage
    default: op
    children:
      votereward.admin.fakevote:
        description: Allows to use /votereward fakevote
        default: op
      votereward.admin.bag:
        description: Allows bag admin commands usage
        default: op
        children:
          votereward.admin.bag.get:
            description: Allows using /votereward admin bag get
            default: op
          votereward.admin.bag.see:
            description: Allows using /votereward admin bag see
            default: op
      votereward.admin.rewardsgroups:
        description: Allows admin commands for the rewards groups
        default: op
        children:
          votereward.admin.rewardsgroups.create:
            description: Allows using /votereward admin rewardsgroups create
            default: op
          votereward.admin.rewardsgroups.list:
            description: Allows using /votereward admin rewardsgroups list
            default: op
          votereward.admin.rewardsgroups.activate:
            description: Allows using /votereward admin rewardsgroups activate
            default: op