main: fr.lataverne.votereward.VoteReward

name: VoteReward

description: Manage the vote rewards and the bags

authors:
  - syuko

version: ${version}

api-version: 1.18

softdepend:
  - ItemReward

  votereward.topvote:
    description: Allows using /votereward topvote
    default: true
  votereward.vote:
    description: Allows using /votereward vote
    default: true